version: '3'
services:

  rabbitmq_xptr:
    image: kbudde/rabbitmq-exporter
    network_mode: "host"

  memcached_xptr:
    image: quay.io/prometheus/memcached-exporter:latest
    network_mode: "host"

  vprodb:
    image: vprofile/vprofiledb:V1
    network_mode: "host"
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

  vprocache01:
    image: memcached
    network_mode: "host"
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    network_mode: "host"
    ports:
      - "15672:15672"
      - "25672:25672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp:
    image: 192.168.3.91:8082/vpro-docker-release/vproapp:V2
    network_mode: "host"
    ports:
      - "8098:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps

  vproweb:
    image: vprofile/vprofileweb:V1
    network_mode: "host"
    ports:
      - "80:80"
volumes:
  vprodbdata: {}
  vproappdata: {}
