- name: Deploy containers
  hosts: appsrvgrp
  become: yes

  tasks:
    - name: Create remote temp dir
      file:
        path: /tmp/vproapp
        state: directory

    - name: Copy Docker Compose files
      copy:
        src: files/docker-compose.yml
        dest: /tmp/vproapp/docker-compose.yml

    - name: Setup with docker-compose
      community.docker_compose:
        project_src: /tmp/vproapp
        files: docker-compose.yml
        remote_src: true
      register: contdeploy

    - name: Display result
      debug:
        msg: "Log from docker-compose: \n {{contdeploy}}\n"
      when: contdeploy.changed = true

