- name: Deploy containers
  hosts: appsrvgrp
  become: yes

  pre_tasks:
    - wait_for_connection: { timeout: 300 }
    - setup:

  vars:
    docker_sdk_for_python_install: True
    docker_compose_install: True
    docker_daemon_config:
      default-address-pools:
        - { base: 172.16.0.0/16, size: 26 }
      log-driver: "json-file"
      log-opts:
        max-size: "10m"
        max-file: "3"

  tasks:
    - name: Install Docker
      import_role:
        name: docker

    - name: Create remote temp dir
      file:
        path: /tmp/vproapp
        state: directory

    - name: Copy Docker Compose files
      copy:
        src: files/docker-compose.yml
        dest: /tmp/vproapp/docker-compose.yml

    - name: Setup with docker-compose
      docker_compose:
        project_src: /tmp/vproapp
        files: docker-compose.yml
      register: contdeploy

    - name: Display result
      debug:
        msg: "Log from docker-compose: \n {{contdeploy}}\n"
      when: contdeploy.changed = true

